zwsp <- "\u200b"

write_ledger <- function(lines) {
  path <- withr::local_tempfile(fileext = ".md", .local_envir = parent.frame())
  writeLines(lines, path)
  path
}

ledger_lines <- c(
  "# Assumptions: demo",
  "",
  "<!-- Generated by `oai assumptions demo --write` from assumptions.toml. Do not edit. -->",
  "",
  "1 confirmed",
  "",
  "## Confirmed (1)",
  "",
  "| Key | Value | Source | Rationale |",
  "|---|---|---|---|",
  "| `cohort.min_age` | `50` | p.1661 | |",
  "| `exposure.category_midpoints` | `{\"years\": [3.0, 8.0]}` | as `lo2022.walker_item` | uses 0.5 |",
  "",
  "## Variants",
  "",
  "| Variant | Sets | Description |",
  "|---|---|---|",
  "| `both` | `outcomes.replacement_is_structural_worsening = false`; `device.wave_combination = 06` | two |"
)

test_that("ledger_markdown drops the title and the generated-by comment, keeps the rest", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  expect_false(any(grepl("^# |^<!--", out)))
  expect_equal(out[1], "")
  expect_true("## Confirmed (1)" %in% out)
  expect_true("1 confirmed" %in% out)
})

test_that("a key or identifier span becomes plain text with break points after . and _", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  key <- grep("cohort", out, value = TRUE)
  expect_equal(key, paste0("| cohort.", zwsp, "min_", zwsp, "age | `50` | p.1661 | |"))
  # a source that merely names an identifier is treated the same way
  expect_true(any(grepl(paste0("as lo2022.", zwsp, "walker_", zwsp, "item"), out, fixed = TRUE)))
})

test_that("values that do not look like identifiers (numbers, JSON) stay code spans, untouched", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  expect_true(any(grepl("`50`", out, fixed = TRUE)))
  expect_true(any(grepl("`{\"years\": [3.0, 8.0]}`", out, fixed = TRUE)))
  # the 0.5 in prose is not an identifier and gets no break point
  expect_true(any(grepl("uses 0.5 |", out, fixed = TRUE)))
})

test_that("an identifier-like value loses its code formatting; a value with a hyphen keeps it", {
  out <- ledger_markdown(write_ledger(c(
    "| Key | Value | Source | Rationale |",
    "|---|---|---|---|",
    "| `a.b` | `walker_requires_amount` | | |",
    "| `c.d` | `mean` (choices: mean, 06) | | |",
    "| `e.f` | `non-walker` | | |"
  )))
  expect_equal(out[3], paste0("| a.", zwsp, "b | walker_", zwsp, "requires_", zwsp, "amount | | |"))
  expect_equal(out[4], paste0("| c.", zwsp, "d | mean (choices: mean, 06) | | |"))
  expect_equal(out[5], paste0("| e.", zwsp, "f | `non-walker` | | |"))
})

test_that("a variant's key = value spans stay code, with break points in the key only", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  row <- grep("^\\| both", out, value = TRUE)
  expect_equal(row, paste0(
    "| both | `outcomes.", zwsp, "replacement_", zwsp, "is_", zwsp, "structural_", zwsp, "worsening = false`; ",
    "`device.", zwsp, "wave_", zwsp, "combination = 06` | two |"
  ))
})

test_that("a ledger with no variants or spans passes through minus its header", {
  out <- ledger_markdown(write_ledger(c("# Assumptions: x", "<!-- generated -->", "", "nothing here")))
  expect_equal(out, c("", "nothing here"))
})

ledger_tables <- c(
  "## Confirmed (1)", "",
  "| Key | Value | Source | Rationale |", "|---|---|---|---|", "| `a.b` | `1` | p.1 | |", "",
  "## Variants", "",
  "| Variant | Sets | Description |", "|---|---|---|", "| `v` | `a.b = 2` | two |"
)
separators <- function(lines) lines[grepl("^\\|-", lines)]

test_that("widths rewrite a table's separator row to dashes in those proportions", {
  path <- write_ledger(ledger_tables[1:5])
  out <- ledger_markdown(path, widths = c(5, 5, 9, 4))
  expect_equal(separators(out), "|-----|-----|---------|----|")
  # the rows around the separator are untouched
  expect_equal(out[grepl("^\\| Key", out)], "| Key | Value | Source | Rationale |")
  expect_equal(out[grepl("^\\| a", out)], paste0("| a.", zwsp, "b | `1` | p.1 | |"))
  # without widths the separator stays as written
  expect_equal(separators(ledger_markdown(path)), "|---|---|---|---|")
  expect_equal(separators(ledger_markdown(path, widths = NULL)), "|---|---|---|---|")
})

test_that("small or fractional widths keep their proportions, with at least three dashes a column", {
  path <- write_ledger(ledger_tables[1:5])
  expect_equal(separators(ledger_markdown(path, widths = c(1, 1, 1, 1))), "|---|---|---|---|")
  expect_equal(separators(ledger_markdown(path, widths = c(1.5, 1, 1, 0.5))), "|---------|------|------|---|")
  # only the proportions matter
  expect_equal(separators(ledger_markdown(path, widths = c(50, 50, 90, 40))), "|-----|-----|---------|----|")
})

test_that("a table whose column count differs from the widths is an error", {
  expect_error(ledger_markdown(write_ledger(ledger_tables[1:5]), widths = c(1, 1, 1)),
               "4 columns but widths gives 3")
  expect_error(ledger_markdown(write_ledger(ledger_tables), widths = c(5, 5, 9, 4)),
               "3 columns but widths gives 4")
})

test_that("a list of widths gives each table shape its own, matched by column count", {
  out <- ledger_markdown(write_ledger(ledger_tables), widths = list(c(5, 5, 9, 4), c(2, 1, 3)))
  expect_equal(separators(out), c("|-----|-----|---------|----|", "|------|---|---------|"))
  expect_error(ledger_markdown(write_ledger(ledger_tables), widths = list(c(5, 5, 9, 4), c(1, 1))), "no entry of length 3")
  expect_error(ledger_markdown(write_ledger(ledger_tables), widths = list(c(1, 1), c(2, 2, 2))), "no entry of length 4")
})

test_that("widths must be positive numbers, and a ledger with no table to apply them to is an error", {
  path <- write_ledger(ledger_tables[1:5])
  expect_error(ledger_markdown(path, widths = c(1, 0, 1, 1)), "positive")
  expect_error(ledger_markdown(path, widths = c(1, NA, 1, 1)), "positive")
  expect_error(ledger_markdown(path, widths = "a"), "positive")
  expect_error(ledger_markdown(path, widths = list(c(1, 1), c(1, 1))), "different lengths")
  expect_error(ledger_markdown(write_ledger(c("# A", "nothing here")), widths = c(1, 1)), "no table")
})
