zwsp <- "\u200b"

write_ledger <- function(lines) {
  path <- withr::local_tempfile(fileext = ".md", .local_envir = parent.frame())
  writeLines(lines, path)
  path
}

ledger_lines <- c(
  "# Assumptions: demo",
  "",
  "<!-- Generated by `oai assumptions demo --write` from assumptions.toml. Do not edit. -->",
  "",
  "1 confirmed",
  "",
  "## Confirmed (1)",
  "",
  "| Key | Value | Source | Rationale |",
  "|---|---|---|---|",
  "| `cohort.min_age` | `50` | p.1661 | |",
  "| `exposure.category_midpoints` | `{\"years\": [3.0, 8.0]}` | as `lo2022.walker_item` | uses 0.5 |",
  "",
  "## Variants",
  "",
  "| Variant | Sets | Description |",
  "|---|---|---|",
  "| `both` | `outcomes.replacement_is_structural_worsening = false`; `device.wave_combination = 06` | two |"
)

test_that("ledger_markdown drops the title and the generated-by comment, keeps the rest", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  expect_false(any(grepl("^# |^<!--", out)))
  expect_equal(out[1], "")
  expect_true("## Confirmed (1)" %in% out)
  expect_true("1 confirmed" %in% out)
})

test_that("a key or identifier span becomes plain text with break points after . and _", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  key <- grep("cohort", out, value = TRUE)
  expect_equal(key, paste0("| cohort.", zwsp, "min_", zwsp, "age | `50` | p.1661 | |"))
  # a source that merely names an identifier is treated the same way
  expect_true(any(grepl(paste0("as lo2022.", zwsp, "walker_", zwsp, "item"), out, fixed = TRUE)))
})

test_that("values stay code spans, untouched", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  expect_true(any(grepl("`50`", out, fixed = TRUE)))
  expect_true(any(grepl("`{\"years\": [3.0, 8.0]}`", out, fixed = TRUE)))
  # the 0.5 in prose is not an identifier and gets no break point
  expect_true(any(grepl("uses 0.5 |", out, fixed = TRUE)))
})

test_that("a variant's key = value spans stay code, with break points in the key only", {
  out <- ledger_markdown(write_ledger(ledger_lines))
  row <- grep("^\\| both", out, value = TRUE)
  expect_equal(row, paste0(
    "| both | `outcomes.", zwsp, "replacement_", zwsp, "is_", zwsp, "structural_", zwsp, "worsening = false`; ",
    "`device.", zwsp, "wave_", zwsp, "combination = 06` | two |"
  ))
})

test_that("a ledger with no variants or spans passes through minus its header", {
  out <- ledger_markdown(write_ledger(c("# Assumptions: x", "<!-- generated -->", "", "nothing here")))
  expect_equal(out, c("", "nothing here"))
})
